### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Maradar** [themoonisacheese/themer.js#1]
Hello as it seems the recent changes in DiscordPTB, Canary and probably the Stable version as well, made this webapp not working.

**Comment by themoonisacheese** [comment]
Fixed with 3.0.

**Comment by themoonisacheese** [comment]
jk ^its ^^not

**Comment by themoonisacheese** [comment]
This has now been fixed on my part.

The rest is just waiting for gitcdn.xyz to update.
